### ISSUE TITLE
docker is not mounting the source code folder so changes are not mirroed to the container

### ISSUE THREAD

**Issue by coopnickol** [CIMRO/website#1]
OS:  MSW 7 Professional 64
Docker version:
```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:
 OS/Arch:      windows/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:
 OS/Arch:      linux/amd64
```

Docker Compose:
```
version: '2.0'

services:

  client:

    extends:
      file: ./compose/client.yml
      service: client

    environment:
      - NODE_ENV=development

    volumes:
      - ./client:/home/app
      - /home/app/node_modules
```

This should work...maybe need to wait until updating OS to 10, but this is bothering me that the issue cannot be resolved as of yet.
